# Generated by Django 4.2.6 on 2023-10-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarTires",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nimi")),
                (
                    "sureName",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Sukunimi"
                    ),
                ),
                (
                    "carNo",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Re. Numero"
                    ),
                ),
                (
                    "phoneNumber",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Puh. Numero",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Lisä tiedot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Re.",
                "verbose_name_plural": "Car Tires",
            },
        ),
    ]
